// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['main']['App']['Abort']();
}

export function AddWorkspace(arg1) {
  return window['go']['main']['App']['AddWorkspace'](arg1);
}

export function AddWorkspaceDialog() {
  return window['go']['main']['App']['AddWorkspaceDialog']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function OpenWorkspace() {
  return window['go']['main']['App']['OpenWorkspace']();
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SendDialogResponse(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendDialogResponse'](arg1, arg2, arg3, arg4);
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}

export function SetModel(arg1, arg2) {
  return window['go']['main']['App']['SetModel'](arg1, arg2);
}

export function SetThinking(arg1) {
  return window['go']['main']['App']['SetThinking'](arg1);
}

export function StartPi() {
  return window['go']['main']['App']['StartPi']();
}

export function StopPi() {
  return window['go']['main']['App']['StopPi']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}
