// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Abort():Promise<void>;

export function AddWorkspace(arg1:string):Promise<main.WorkspaceListResult>;

export function AddWorkspaceDialog():Promise<main.WorkspaceListResult>;

export function GetSnapshot():Promise<main.Snapshot>;

export function GetWorkspace():Promise<main.WorkspaceInfo>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function ListWorkspaces():Promise<main.WorkspaceListResult>;

export function NewSession():Promise<void>;

export function OpenWorkspace():Promise<main.WorkspaceInfo>;

export function ResumeSession(arg1:string):Promise<main.Snapshot>;

export function SendDialogResponse(arg1:string,arg2:string,arg3:any,arg4:boolean):Promise<void>;

export function SendPrompt(arg1:string):Promise<void>;

export function SetModel(arg1:string,arg2:string):Promise<void>;

export function SetThinking(arg1:string):Promise<void>;

export function StartPi():Promise<void>;

export function StopPi():Promise<void>;

export function SwitchWorkspace(arg1:string):Promise<main.Snapshot>;
